#ifndef _H_VARIABLEHUB_
#define _H_VARIABLEHUB_

#include <ntifs.h>

NTSTATUS  VariableHub_Init();
ULONG_PTR VariableHub_GetById(ULONG Id);

enum enumVariableHubId
{
    enumVarHubId_Begin = 0,

    // Offset
    enumVarHubId_Offset_KTHREAD_PreviousMode = 1,
    enumVarHubId_Offset_KTHREAD_Win32Thread,
    enumVarHubId_Offset_KTHREAD_ApcStateIndex,
    enumVarHubId_Offset_KTHREAD_Process,
    enumVarHubId_Offset_EPROCESS_ImageFileName,
    enumVarHubId_Offset_EPROCESS_SeAuditProcessCreationInfo,
    enumVarHubId_Offset_EPROCESS_ActiveProcessLinks,
    enumVarHubId_Offset_EPROCESS_UniqueProcessId,
    enumVarHubId_Offset_EPROCESS_InheritedFromUniqueProcessId,
    enumVarHubId_Offset_EPROCESS_CreateTime,

    // Kernel Exported function
    enumVarHubId_ExportedAPI_ExAllocatePoolWithTag = 1024,
    enumVarHubId_ExportedAPI_ExFreePoolWithTag,
    enumVarHubId_ExportedAPI_MmCopyVirtualMemory,
    enumVarHubId_ExportedAPI_ObCreateObject,
    enumVarHubId_ExportedAPI_ObInsertObject,
    enumVarHubId_ExportedAPI_ObReferenceObjectByHandle,
    enumVarHubId_ExportedAPI_ObfDereferenceObject,
    enumVarHubId_ExportedAPI_PsAcquireProcessExitSynchronization,
    enumVarHubId_ExportedAPI_PsReleaseProcessExitSynchronization,
    enumVarHubId_ExportedAPI_ObGetObjectType,
    enumVarHubId_ExportedAPI_ObRegisterCallbacks,
    enumVarHubId_ExportedAPI_ObUnRegisterCallbacks,
    enumVarHubId_ExportedAPI_PsLookupProcessByProcessId,
    enumVarHubId_ExportedAPI_PsGetThreadProcessId,
    enumVarHubId_ExportedAPI_PsGetProcessImageFileName,
    enumVarHubId_ExportedAPI_MmIsAddressValid,
    enumVarHubId_ExportedAPI_PsGetProcessId,
    enumVarHubId_ExportedAPI_KeGetCurrentIrql,
    enumVarHubId_ExportedAPI_IoGetCurrentProcess,
    enumVarHubId_ExportedAPI_PsGetCurrentProcessId,
    enumVarHubId_ExportedAPI_PsSetCreateProcessNotifyRoutineEx,
    enumVarHubId_ExportedAPI_PsSetCreateThreadNotifyRoutine,
    enumVarHubId_ExportedAPI_PsRemoveCreateThreadNotifyRoutine,
    enumVarHubId_ExportedAPI_IoCreateDevice,
    enumVarHubId_ExportedAPI_IoDeleteDevice,
    enumVarHubId_ExportedAPI_IoCreateSymbolicLink,
    enumVarHubId_ExportedAPI_IoDeleteSymbolicLink,
    enumVarHubId_ExportedAPI_ExEnumHandleTable,
    enumVarHubId_ExportedAPI_RtlEqualUnicodeString,
    enumVarHubId_ExportedAPI_PsRemoveLoadImageNotifyRoutine,
    enumVarHubId_ExportedAPI_PsSetLoadImageNotifyRoutine,
    enumVarHubId_ExportedAPI_PsSetCreateProcessNotifyRoutine,
    enumVarHubId_ExportedAPI_KeEnterCriticalRegion,
    enumVarHubId_ExportedAPI_KeLeaveCriticalRegion,
    enumVarHubId_ExportedAPI_ExfAcquirePushLockExclusive,
    enumVarHubId_ExportedAPI_ExfReleasePushLockExclusive,
    enumVarHubId_ExportedAPI_ExfAcquirePushLockShared,
    enumVarHubId_ExportedAPI_ExfReleasePushLockShared,
    enumVarHubId_ExportedAPI_KeAcquireInStackQueuedSpinLock,
    enumVarHubId_ExportedAPI_KeReleaseInStackQueuedSpinLock,
    enumVarHubId_ExportedAPI_ExInitializeResourceLite,
    enumVarHubId_ExportedAPI_ExDeleteResourceLite,
    enumVarHubId_ExportedAPI_ExAcquireResourceSharedLite,
    enumVarHubId_ExportedAPI_ExAcquireResourceExclusiveLite,
    enumVarHubId_ExportedAPI_ExReleaseResourceLite,
    enumVarHubId_ExportedAPI_PsLookupThreadByThreadId,
    enumVarHubId_ExportedAPI_PsCreateSystemThread,
    enumVarHubId_ExportedAPI_KeWaitForSingleObject,
    enumVarHubId_ExportedAPI_ZwClose,
    enumVarHubId_ExportedAPI_ExRaiseStatus,
    enumVarHubId_ExportedAPI_KeStackAttachProcess,
    enumVarHubId_ExportedAPI_KeUnstackDetachProcess,
    enumVarHubId_ExportedAPI_MmMapLockedPagesSpecifyCache,
    enumVarHubId_ExportedAPI_MmProbeAndLockPages,
    enumVarHubId_ExportedAPI_MmUnmapLockedPages,
    enumVarHubId_ExportedAPI_MmUnlockPages,
    enumVarHubId_ExportedAPI_ProbeForRead,
    enumVarHubId_ExportedAPI_ProbeForWrite,
    enumVarHubId_ExportedAPI_ExfUnblockPushLock,
    enumVarHubId_ExportedAPI_IoAllocateMdl,
    enumVarHubId_ExportedAPI_IoFreeMdl,
    enumVarHubId_ExportedAPI_ObOpenObjectByPointer,
    enumVarHubId_ExportedAPI_ObReferenceObjectByName,
    enumVarHubId_ExportedAPI_KeIpiGenericCall,
    enumVarHubId_ExportedAPI_KeQueryActiveProcessorCountEx,
    enumVarHubId_ExportedAPI_KeGenericCallDpc,
    enumVarHubId_ExportedAPI_KeSignalCallDpcSynchronize,
    enumVarHubId_ExportedAPI_KeSignalCallDpcDone,
    enumVarHubId_ExportedAPI_PsTerminateSystemThread,
    enumVarHubId_ExportedAPI_KeGetProcessorNumberFromIndex,
    enumVarHubId_ExportedAPI_KeSetSystemGroupAffinityThread,
    enumVarHubId_ExportedAPI_KeRevertToUserGroupAffinityThread,
    enumVarHubId_ExportedAPI_KeInitializeDpc,
    enumVarHubId_ExportedAPI_KeSetImportanceDpc,
    enumVarHubId_ExportedAPI_KeSetTargetProcessorDpc,
    enumVarHubId_ExportedAPI_KeInsertQueueDpc,
    enumVarHubId_ExportedAPI_KeInitializeThreadedDpc,
    enumVarHubId_ExportedAPI_KeRaiseIrqlToDpcLevel,
    enumVarHubId_ExportedAPI_KeGetCurrentProcessorNumberEx,
    enumVarHubId_ExportedAPI_MmGetVirtualForPhysical,
    enumVarHubId_ExportedAPI_RtlUpcaseUnicodeChar,
    enumVarHubId_ExportedAPI_ObCloseHandle,
    enumVarHubId_ExportedAPI_RtlQueryAtomInAtomTable,

    // SSDT function
    enumVarHubId_SsdtAPI_NtQuerySystemInformation = 2048,
    enumVarHubId_SsdtAPI_NtQueryInformationProcess,
    enumVarHubId_SsdtAPI_NtQueryDirectoryObject,
    enumVarHubId_SsdtAPI_NtOpenDirectoryObject,
    enumVarHubId_SsdtAPI_NtClose,
    enumVarHubId_SsdtAPI_NtYieldExecution,
    enumVarHubId_SsdtAPI_NtWaitForSingleObject,
    enumVarHubId_SsdtAPI_NtQueryVirtualMemory,
    enumVarHubId_SsdtAPI_NtProtectVirtualMemory,

    // End
    enumVarHubId_End,
};

#endif // _H_VARIABLEHUB_
